name: Kitemaker Ticket archiver

on:
    workflow_dispatch:


jobs:
    send-ticket:
        uses: gravitl/devops/.github/workflows/makekitemakerticket.yml@master
        with:
            title: ${{ github.event.issue.title }}
            body: ${{ github.event.issue.body }}
            repo_name: ${{ github.event.repository.name }}
            issue_number: ${{ github.event.issue.number }}
        secrets: inherit