name: Release Netmaker-UI
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:

  release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netmaker-ui-2
          ref: develop
      - name: Setup git
        run: |
          git config --global user.name "Gravitl"
          git config --global user.email "info@netmaker.io"
      - name: Create Release Branch
        run: |
          git switch -c release-${{ inputs.version }}
          git tag -f ${{ inputs.version }}
          git push origin release-${{ inputs.version }}
          git push origin ${{ inputs.version }}

  docker:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: gravitl/netmaker-ui-2
          ref: release-${{ inputs.version }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64, linux/arm/v7
          push: true
          tags: |
            gravitl/netmaker-ui:${{ inputs.version }}
            gravitl/netmaker-ui:latest
            
  pull-request:
    needs: release-branch
    runs-on: ubuntu-latest
    steps:
      - name: create pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST \
          -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'  \
          /repos/gravitl/netmaker-ui-2/pulls \
          -f title='${{ inputs.version }}' \
          -f head='release-${{ inputs.version }}' \
          -f base="master"
